name: Self hosted runner
#run-name: ${{ github.actor }} is learning GitHub Actions
on: [workflow_dispatch]
jobs:
  DEV:
    runs-on: self-hosted
    steps:
      - run: |
          pwd 
          hostname


